{{- if .Values.scaledObject.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-scaler
spec:
  # Name of the deployment you want to scale
  scaleTargetRef:
    name: {{ .Values.scaledObject.scaleTargetRefName }}
  pollingInterval: {{ .Values.scaledObject.pollingInterval | default 30 }}
  cooldownPeriod:  {{ .Values.scaledObject.cooldownPeriod | default 300 }}
  minReplicaCount: {{ .Values.scaledObject.minReplicaCount | default 2 }}        # Optional. Default: 0
  maxReplicaCount: {{ .Values.scaledObject.maxReplicaCount | default 9 }}
  triggers:
  {{- if eq .Values.scaledObject.triggerType "external"}}
    - type: {{ .Values.scaledObject.triggerType }}
      # metricType: Value
      metadata:
        scalerAddress: {{ default .Values.scaledObject.scalerAddress }}
  {{- end }}
  {{- if eq .Values.scaledObject.triggerType "metrics-api" }}
    - type: {{ .Values.scaledObject.triggerType }}
      metricType: Value
      metadata:
        targetValue: "1"
        activationTargetValue: "1"
        url: {{ default .Values.scaledObject.scalerAddress }}
        valueLocation: 'desiredReplicas'
  {{- end }}
{{- end }}