version: '3'

vars:
  CYAN: tput setaf 6
  RED: tput setaf 1
  YELLOW: tput setaf 3
  GREEN: tput setaf 2
  BLUE: tput setaf 1
  PURPLE: tput setaf 5
  BG_B: tput setab 0
  BOLD: tput bold
  RESET: tput sgr0
  CLEAR: tput reset
  INT_REGISTRY: registry.localhost:5002
  PATH_ERROR: is not installed or correctly configured in PATH.
  ENV: local

dotenv: [ '.env' ]

# silent: true

tasks:


  run-local:
    desc: Build the Python - api / master application
    cmds:
      - poetry install --no-root
      - poetry env info
      - poetry run uvicorn api:app --reload 
  
  run-api-local:
    cmds:
      - task: run-local

  run-worker-local:
    desc: Build the Python - worker application
    cmds:
      - poetry install --no-root
      - poetry env info
      - poetry run uvicorn worker:app --reload 

  docker-build:
    desc: Build a Docker container
    cmds:
      - docker build -t '{{.VENDOR_NAME}}/{{.PROJECT_NAME}}:{{.VERSION}}' .

  deploy_keda:
    # internal: true
    desc: install keda
    cmds:
      - helm repo add kedacore https://kedacore.github.io/charts
      - helm upgrade --install keda kedacore/keda --namespace keda --create-namespace
 
  deploy_demo_app:
    # internal: true
    desc: install demo_app
    cmds:
      - kubectl apply -k ./deploy

  port_forward_demo_app:
    desc: port-forward to demo_app
    cmds:
      - kubectl port-forward -n keda-poc svc/api 8000:80 -n keda-poc

  deploy_monitor:
    desc: deploy prometheus
    cmds:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm repo update
      - helm upgrade prometheus --install  -f ./deploy/prometheus/values.yaml prometheus-community/prometheus --namespace keda-poc

  port_forward_monitor:
    desc: port-forward to prometheus
    cmds:
      - kubectl port-forward -n keda-poc svc/prometheus-server 9000:80

  launch_demo:
    internal: true
    desc: run-demo
    cmds:
      - task: deploy_keda
      - task: deploy_demo_app

  # utils
  clear:
    internal: true
    cmds:
      - sleep 0.1 && {{.CLEAR}}

  default:
    cmds:
      - task: clear
      - task: launch_demo
