version: '3'

vars:
  CYAN: tput setaf 6
  RED: tput setaf 1
  YELLOW: tput setaf 3
  GREEN: tput setaf 2
  BLUE: tput setaf 1
  PURPLE: tput setaf 5
  BG_B: tput setab 0
  BOLD: tput bold
  RESET: tput sgr0
  CLEAR: tput reset
  INT_REGISTRY: registry.localhost:5002
  PATH_ERROR: is not installed or correctly configured in PATH.
  ENV: local

dotenv: [ '.env' ]

silent: true

tasks:

  run-local:
    desc: Build the Python - api / master application
    cmds:
      - poetry install --no-root
      - poetry env info
      - poetry run uvicorn api:app --reload 

  run-worker-local:
    desc: Build the Python - worker application
    cmds:
      - poetry install --no-root
      - poetry env info
      - poetry run uvicorn worker:app --reload 

  docker-build:
    desc: Build a Docker container
    cmds:
      - docker build -t '{{.VENDOR_NAME}}/{{.PROJECT_NAME}}:{{.VERSION}}' .

  deploy_keda:
    # internal: true
    desc: install keda
    cmds:
      - helm repo add kedacore https://kedacore.github.io/charts
      - helm upgrade --install keda kedacore/keda --namespace keda --create-namespace
 
  deploy_demo_app:
    # internal: true
    desc: install demo_app
    cmds:
      - kubectl apply -k ./deploy

  launch_demo:
    internal: true
    desc: run-demo
    cmds:
      - task: deploy_keda
      - task: deploy_demo_app

  # utils
  clear:
    internal: true
    cmds:
      - sleep 0.1 && {{.CLEAR}}

  default:
    cmds:
      - task: clear
      - task: launch_demo
