apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: keda-poc
  name: keda-poc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: keda-poc
status:
  loadBalancer: {}