apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: docker.io/hagzag/keda-py:latest-8
        name: worker
        ports:
        - name: http
          containerPort: 8000
        command: [ "poetry", "run", "uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "8000"]
        resources: {}