# Default values for wrapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    repository: ghcr.io/hagzag/keda-poc
    tag: v1.5.1

scaledObject:
  enabled: true
  triggerType: metrics-api
  # want the worker name to be set see worker.fullnameOverride: *worker_name
  scaleTargetRefName: &worker_name worker
  # test container / svc ports
  scalerAddress: http://api.keda-poc.svc.cluster.local:9090/scaleJson
  # scalerAddress: scaler.keda-poc.svc.cluster.local:50051
  # scalerAddress: scaler.keda-poc.svc.cluster.local:50052
  pollingInterval: 2  # Optional. Default: 30 seconds
  cooldownPeriod:  10  # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  # maxReplicaCount: 1   # Optional. Default: 9

custom-scaler:
  enabled: false
  fullnameOverride: scaler
  nameOverride: scaler
  service: 
    enabled: true
    port: 50051
    # test container / svc ports
    # port: 50052
    # containerPort: 50051
  env:
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: SCALER_API_EP
    value: "http://api:9090/scale"
  args:
  - poetry
  - run
  - python 
  - src/custom_scaler/grpc_server.py

api:
  enabled: true
  fullnameOverride: api
  service: 
    enabled: true
    port: 9090
  
  args:
  - poetry
  - run
  - uvicorn
  - src.api.main:app
  - --host
  - 0.0.0.0
  - --port 
  - 9090

worker:
  enabled: true
  fullnameOverride: *worker_name
  service: 
    enabled: true
    port: 8080
  replicaCount: 0
  env:
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: REGISTER_EP
    value: "http://api:9090/register"
  args:
  - poetry
  - run
  - uvicorn
  - src.worker.main:app
  - --host
  - 0.0.0.0
  - --port 
  - 8080

metrics-server:
  enabled: false

keda:
  enabled: false

prometheus:
  enabled: false

